Vue naming protocol
Shipstr/guides pull request #4
Opened 2018-09-27 23:56 UTC by mcnelson

First effort at establishing some kind of naming pattern for our Vue apps.

Want to get this out there sooner than later before it grows too much for us to be motivated.

2019-01-14 18:56 UTC, feitla commented on style/vue/README.md
> +**Globally reusable** components, relevant to any area of your app, live in `src/components`. Components that are generic to **one area** of the app and cannot be easily reused anywhere else also liv
these components we are not underscoring

2019-01-14 18:56 UTC, feitla commented on style/vue/README.md
> +### Child components
```suggestion
### Child components/Partials
```

2019-08-06 00:02 UTC, mcnelson commented
Let's get Grant's :+1: on this, Luda if you want to review again, and we'll get this puppy merged.

2019-08-06 16:12 UTC, feitla requested changes

2019-08-06 16:12 UTC, feitla commented on style/vue/README.md
> +- Component filenames are ProperCased and mixins are snake_cased.
not snake_cased but camelCased

2019-08-06 16:12 UTC, feitla commented on style/vue/README.md
> +Mixins also live one level deep in a resourceful directory, for example `src/views/{resourceful name}/formatters.js`. Mixin filenames are snake cased.
mixin filenames are cameCased

2019-08-06 18:37 UTC, feitla approved these changes

2019-08-06 18:37 UTC, merged